version: "3.2"

services:
  app:
    build: .
    ports:
      - 3001:3001
    container_name: vyardage

  tests:
    build: ./e2e/
    container_name: vyardage-test
    environment:
      - CYPRESS_BASE_URL=http://app:3001
    depends_on:
      - app
    volumes:
      - ./e2e/cypress:/e2e/cypress
