version: "3.2"

services:
  app:
    build: .
    ports:
      - 3001:3001
    container_name: vyardage-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:12.2
    container_name: vyardage-db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/data
    ports:
      - 5432:5432

  tests:
    build: ./e2e/
    container_name: vyardage-test
    environment:
      - CYPRESS_BASE_URL=http://app:3001
    depends_on:
      - app
    volumes:
      - ./e2e/cypress:/e2e/cypress
