version: "3.2"

services:
  app:
    build: .
    ports:
      - 3001:3001
    container_name: vyardage-app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SESSION_SECRET=asd
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules/
    command: npm run start:dev

  test-dev-app:
    build: .
    ports:
      - 3001:3001
    container_name: vyardage-test-dev-app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@test-db:5432/postgres
      - SESSION_SECRET=asd
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules/
    command: npm run start:dev

  test-app:
    build: .
    ports:
      - 3001:3001
    container_name: test-app
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@test-db:5432/postgres
      - SESSION_SECRET=asd
    volumes:
      - /usr/src/app/server/node_modules/
    command: npm run start:test

  db:
    image: postgres:12.2
    container_name: vyardage-db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/data
    ports:
      - 5432:5432

  test-db:
    image: postgres:12.2
    container_name: test-db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  tests:
    build: ./e2e/
    container_name: vyardage-test
    environment:
      - CYPRESS_BASE_URL=http://test-app:3001
    depends_on:
      - test-db
      - test-app
    volumes:
      - ./e2e/cypress:/e2e/cypress

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080