version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

executors:
  test-exec:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  run-tests:
    executor: test-exec
    steps:
      - checkout
      #- run: npm run install:e2e
      #- run: docker-compose up -d test-db test-app
      #- run: timeout 5m bash -c 'until $(curl --output /dev/null --silent --fail http://localhost:3001); do printf .; sleep 5; done'
      #- run: npm run test:ci
      - run: docker-compose run tests
      - store_artifacts:
          path: e2e/cypress/videos
      - store_artifacts:
          path: e2e/cypress/screenshots

workflows:
  heroku-deploy:
    jobs:
      - run-tests
      - heroku/deploy-via-git:
          maintenance-mode: true
          filters:
            branches:
              only: master
          requires:
            - run-tests
      - heroku/deploy-via-git:
          maintenance-mode: true
          app-name: $HEROKU_APP_NAME_STAGING
          filters:
            branches:
              only: trunk
          requires:
            - run-tests
