version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

executors:
  test-exec:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  run-tests:
    executor: test-exec
    steps:
      - checkout
      - run: npm run install:e2e
      - run: docker-compose up -d
      - run: timeout 5m bash -c 'until $(curl --output /dev/null --silent --fail http://localhost:3001); do printf .; sleep 5; done'
      - run: npm run test

workflows:
  heroku-deploy:
    jobs:
      - run-tests
      - heroku/deploy-via-git:
          filters:
            branches:
              only: master
          requires:
            - run-tests
